---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: amsy810@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testbed.35.221.71.44.nip.io
  namespace: infra
spec:
  secretName: testbed-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - testbed.35.221.71.44.nip.io
  - argocd.35.221.71.44.nip.io
  - tekton.35.221.71.44.nip.io
  - harbor.35.221.71.44.nip.io
  - notary.35.221.71.44.nip.io
  - dashboard.35.221.71.44.nip.io
  - rook.35.221.71.44.nip.io
  - prometheus.35.221.71.44.nip.io
  - grafana.35.221.71.44.nip.io
  - alertmanager.35.221.71.44.nip.io
  - weave-scope.35.221.71.44.nip.io
  - yugabyte.35.221.71.44.nip.io
  - minio.35.221.71.44.nip.io
  commonName: testbed.35.221.71.44.nip.io
